<?php $pageTitle = 'Invoice - ' . htmlspecialchars($invoice['invoice_number']); ?>

<div class="container mt-4 invoice-print">
    <div class="card">
        <div class="card-body">
            <div class="row mb-4">
                <div class="col-6">
                    <h2 class="text-primary">INVOICE</h2>
                    <p class="mb-0"><strong>Invoice #:</strong> <?php echo htmlspecialchars($invoice['invoice_number']); ?></p>
                    <p class="mb-0"><strong>Date:</strong> <?php echo date('M d, Y H:i', strtotime($invoice['created_at'])); ?></p>
                </div>
                <div class="col-6 text-end">
                    <h4><?php echo htmlspecialchars($APP_NAME); ?></h4>
                    <p class="mb-0">114-0031 Higashi Tabata 2-3-1</p>
                    <p class="mb-0">Otsu building 101</p>
                    <p class="mb-0">Tel: 080-3408-8044</p>
                </div>
            </div>
            <hr>
            <?php if ($invoice['customer_name'] || $invoice['customer_phone']): ?>
            <div class="row mb-4">
                <div class="col-12">
                    <h5>Customer Information</h5>
                    <?php if ($invoice['customer_name']): ?><p class="mb-0"><strong>Name:</strong> <?php echo htmlspecialchars($invoice['customer_name']); ?></p><?php endif; ?>
                    <?php if ($invoice['customer_phone']): ?><p class="mb-0"><strong>Phone:</strong> <?php echo htmlspecialchars($invoice['customer_phone']); ?></p><?php endif; ?>
                </div>
            </div>
            <hr>
            <?php endif; ?>
            <div class="table-responsive mb-4">
                <table class="table table-bordered">
                    <thead class="table-light"><tr><th>#</th><th>Product</th><th>Barcode</th><th class="text-end">Unit Price</th><th class="text-center">Quantity</th><th class="text-end">Total</th></tr></thead>
                    <tbody>
                        <?php foreach ($items as $index => $item): ?>
                        <tr>
                            <td><?php echo $index + 1; ?></td>
                            <td><?php echo htmlspecialchars($item['product_name']); ?></td>
                            <td><code><?php echo htmlspecialchars($item['barcode']); ?></code></td>
                            <td class="text-end">¥<?php echo number_format($item['unit_price'], 0); ?></td>
                            <td class="text-center"><?php echo $item['quantity']; ?></td>
                            <td class="text-end">¥<?php echo number_format($item['line_total'], 0); ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="col-md-6"><p><strong>Payment Method:</strong> <?php echo htmlspecialchars($invoice['payment_method']); ?></p></div>
                <div class="col-md-6">
                    <table class="table table-sm">
                        <tr><td class="text-end"><strong>Subtotal:</strong></td><td class="text-end">¥<?php echo number_format($invoice['subtotal'], 0); ?></td></tr>
                        <?php if ($invoice['tax'] > 0): ?><tr><td class="text-end"><strong>Tax:</strong></td><td class="text-end">¥<?php echo number_format($invoice['tax'], 0); ?></td></tr><?php endif; ?>
                        <?php if ($invoice['discount'] > 0): ?><tr><td class="text-end"><strong>Discount:</strong></td><td class="text-end">-¥<?php echo number_format($invoice['discount'], 0); ?></td></tr><?php endif; ?>
                        <tr class="table-success"><td class="text-end"><h5>Total:</h5></td><td class="text-end"><h5>¥<?php echo number_format($invoice['total_amount'], 0); ?></h5></td></tr>
                        <tr><td class="text-end"><strong>Amount Paid:</strong></td><td class="text-end">¥<?php echo number_format($invoice['amount_paid'], 0); ?></td></tr>
                        <tr><td class="text-end"><strong>Change:</strong></td><td class="text-end">¥<?php echo number_format($invoice['change_amount'], 0); ?></td></tr>
                    </table>
                </div>
            </div>
            <hr>
            <div class="text-center mt-4">
                <p class="mb-0">Thank you for your business!</p>
                <p class="text-muted small">Generated by <?php echo htmlspecialchars($APP_NAME); ?></p>
            </div>
            <div class="text-center mt-4 d-print-none">
                <button class="btn btn-primary" onclick="window.print()"><i class="bi bi-printer"></i> Print Invoice</button>
                <a href="<?php echo Router::url('/shop/pos'); ?>" class="btn btn-secondary"><i class="bi bi-arrow-left"></i> Back to POS</a>
            </div>
        </div>
    </div>
</div>

<style>
@media print { .navbar, .btn, .footer, .alert, .d-print-none { display: none !important; } .card { box-shadow: none; border: 1px solid #ddd; } }
</style>
